---
    - hosts: webservers
      become: true
      gather_facts: false

      tasks:
        - name: Install Nginx
          apt:
            name: nginx
            state: present
        - name: Install php
          apt:
            name: php
            state: present
        - name: Install php7.4-fpm
          apt:
            name: php7.4-fpm
            state: present
        - name: Copy index.php file to html folder
          copy:
            src: index.php
            dest: /var/www/html
        - name: Copy nginx configuration file
          template:
            src: nginx.cfg.j2
            dest: /etc/nginx/sites-available/default
        - name: Restart Nginx
          service:
            name: nginx
            state: restarted

    - hosts: haproxy
      become: true
      gather_facts: false

      tasks:
        - name: install haproxy
          apt:
            name: haproxy
            state: present
        - name: Copy haproxy configuration file
          template:
            src: haproxy.cfg.j2
            dest: /etc/haproxy/haproxy.cfg
        - name: Start haproxy
          systemd:
            name: haproxy
            state: started
            enabled: true                                                                                                                                        49,25         All
